version: "3.3"
services:
  proxy:
    image: "traefik:latest"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      - ./static.yaml:/etc/traefik/traefik.yaml
      - ./certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      - "traefik.http.routers.proxy-insecure.entrypoints=web"
      - "traefik.http.routers.proxy-insecure.middlewares=redirect-to-https"

      - "traefik.http.routers.proxy.entrypoints=web-secure"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.routers.proxy.tls=true"
      - "traefik.http.routers.proxy.middlewares=redirect-to-https"
    networks:
      - proxy
  whoami:
    image: containous/whoami:v1.3.0
    networks:
      - proxy
    labels:
      - "traefik.http.routers.whoami-insecure.entrypoints=web"
      - "traefik.http.routers.whoami-insecure.middlewares=redirect-to-https"

      - "traefik.http.routers.whoami.tls=true"
networks:
  proxy:
    external: true